// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATSjk2FMdtoHbj7-w1TZd4IgixrJmpuMA',
    appId: '1:144521776715:web:e91ec061920d6e953b87ce',
    messagingSenderId: '144521776715',
    projectId: 'shikshalit-cd606',
    authDomain: 'shikshalit-cd606.firebaseapp.com',
    storageBucket: 'shikshalit-cd606.firebasestorage.app',
    measurementId: 'G-VN8VGXEJNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-LWF3SMDA7okRNLSYUYJv-lgCUM48WWI',
    appId: '1:144521776715:android:7663e6cfa25cb2183b87ce',
    messagingSenderId: '144521776715',
    projectId: 'shikshalit-cd606',
    storageBucket: 'shikshalit-cd606.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKFvvU2tcv5u4OxItiWKXZq-349hejBS4',
    appId: '1:144521776715:ios:1567821eec4cd0923b87ce',
    messagingSenderId: '144521776715',
    projectId: 'shikshalit-cd606',
    storageBucket: 'shikshalit-cd606.firebasestorage.app',
    iosBundleId: 'com.example.literacyCheck',
  );
}
